[package]
name = "medical-cds-hook"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "0.13.0"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }

tokio = { version = "1", features = ["macros"] }
